#! /bin/sh

##############################################
################ BSPWM-config ################
##############################################

pgrep -x sxhkd > /dev/null || sxhkd &

# workspaces
bspc monitor -d 1 2 3 4 

# window borders
bspc config focused_border_color "#61afef"
bspc config normal_border_color "#1f222b"
bspc config border_width 2
bspc config borderless_monocle true

# fix pointer
xsetroot -cursor_name left_ptr

# gaps
bspc config gapless_monocle true
bspc config window_gap 10

# start resources
xrdb merge ~/.Xresources

# load scripts
~/Documents/Systems/Hotkeys/change_background_sxhkd.sh &
~/.config/bspwm/polybar/launch.sh &

# autostart
# picom --config $HOME/.config/bspwm/picom/main.conf &
alacritty &
dunst -config $HOME/.config/bspwm/dunst/dunstrc &

